@Backend2Project_HostAddress = http://localhost:8000

GET {{Backend2Project_HostAddress}}/api/products/
Accept: application/json

###

GET {{Backend2Project_HostAddress}}/api/products?page=2&pageSize=10
Accept: application/json


### Token
POST {{Backend2Project_HostAddress}}/api/auth/token/
Accept: application/json
Content-Type: application/json
{
  "username": "admin",
  "password": "admin"
}